apiVersion: v1
kind: Service
metadata:
  name: devops-task-service
  namespace: devops-task-namespace
spec:
  selector:
    app: devops-task
  type:  NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  devops-task-deployment
  labels:
    app: devops-task
  namespace: devops-task-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-task
  template:
    metadata:
      labels:
        app: devops-task
    spec:
      containers:
      - image: ankitjethi/devops-task:latest
        name: devops-task
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
      restartPolicy: Always
