apiVersion: v1
kind: Service
metadata:
  name: devops-task-service
  namespace: devops-task-namespace
spec:
  selector:
    app: devops-task
    version: "${env.BUILD_NUMBER}"
  type:  NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
